name: Build-Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-lint:
    name: build-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: npm ci

      - name: Build
        run: npx turbo build
        
      - name: Run lint
        run: npx turbo lint
